### ISSUE TITLE
FileNotFoundError: [Errno 2] 'model/BirdNET_Soundscape_Model.pkl'

### ISSUE THREAD

**Issue by PyKoch** [kahst/BirdNET#6]
I think BirdNET is so cool! Sadly I can't get it to run on OSX yet. 

After installation on OSX 10.14.6 I get this error message: 
FileNotFoundError: [Errno 2] No such file or directory: 'model/BirdNET_Soundscape_Model.pkl'

This might well be something minor, but I am not sure how to fix it. Of course this is so specialised that I could not find any solution on Google. 

Here is what I entered: 
`python3 analyze.py --i example/` 

> FILES IN DATASET: 2 
LOADING SNAPSHOT BirdNET_Soundscape_Model.pkl ... Traceback (most recent call last):
  File "analyze.py", line 292, in <module>
    main()
  File "analyze.py", line 266, in main
    test_function = loadModel()
  File "analyze.py", line 37, in loadModel
    snapshot = model.loadSnapshot('model/BirdNET_Soundscape_Model.pkl')
  File "/Users/vk0604/BirdNET/model/model.py", line 28, in loadSnapshot
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'model/BirdNET_Soundscape_Model.pkl'

**Comment by PyKoch** [comment]
I just realised that I could run the command 
`wget https://tuc.cloud/index.php/s/m9smX4FkqmJaxLW/download -O model/BirdNET_Soundscape_Model.pkl`
inside the 'fetch_model.sh' script manually. That solved the issue for me.

**Comment by ArKornreich** [comment]
Hello! I hope someone is still here!

I, too, am encountering issues with this file.

I keep encountering an error related to this missing model file: BirdNET_Soundscape_Model.pkl. It seems that this file is crucial for the analysis, but I’ve had difficulty locating and downloading it. I tried using the fetch_model.sh script, but it didn’t execute as expected. I also attempted to manually download the file via a provided link, but the link appears to be broken or unavailable.

Is there anything I can do?

**Comment by kahst** [comment]
Ah, apologies for the delayed response. We're not actively tracking issues for this repo. It seems the share link was broken, and I updated the URL. Can you please give it a try and see if you can download and run the model? Also, please don't use this repo for any kind of production system or research, make sure to transition to our [BirdNET-Analyzer repo](https://github.com/kahst/BirdNET-Analyzer) which we actively maintain.
